version: 2.1
commands:
  setup-environment:
    description: Installs required dependincies and connect up any required secrets
    steps:
      - run:
          name: Install terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            unzip terraform_0.12.24_linux_amd64.zip
            chmod +x terraform 
            sudo mv terraform /usr/local/bin/terraform
            cd / && terraform -v

      - run:
          name: Install ansible
          command: |
            sudo apt update -y
            sudo apt install -y software-properties-common
            sudo apt-add-repository --yes --update ppa:ansible/ansible
            sudo apt install -y ansible

jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup-cd

      - add_ssh_keys:
          fingerprints:
            - "3f:2c:59:5a:e9:bd:90:ee:42:40:43:3b:33:73:01:4a"

      - run:
          name: create aws infrastructure
          command: |
            make up

      - run:
          name: destroy aws infrastructure
          command: |
            make down


      # - run:
      #     name: copy project onto EC2 machine
      #     command: |
      #       scp -o StrictHostKeyChecking=no -r ./majorproject-5-wed-16-30-5 ec2-user@3.81.30.66:~/

      # - run:
      #     name: run ansible playbook
      #     command: |
      #       cd ansible
      #       sudo chmod a-x inventory.yml
      #       ansible-playbook -i inventory.yml -e 'record_host_keys=True' -u ec2-user playbook.yml
      #     environment:
      #       ANSIBLE_HOST_KEY_CHECKING: False

workflows:
  version: 2
  pipeline:
    jobs:
      - build
