version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:

    working_directory: ~/src
    docker:
    - image: circleci/openjdk:8-jdk-streach
    - image: circleci/postgres:9.6.3-alpine
    enviroment:
     POSTGRES_USER: root
     POSTGRES_DB: circleci_test

    steps:
      - checkout
      - restore_cache:
         key: circleci_demo-java-spring-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci_demo-java-spring-{{ checksum "pom.xml"}}

      - run: mvn package

      - store_test_result:
          path: tearget/surefire-reports

      - store_artifacts:
          path: tearget/demo-java-spring-0.0.1-SANPSHOT.jar
    



 

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test